import type { Member } from './types'

const now = new Date()
const isoNow = now.toISOString().split('T')[0]

function daysAgo(n: number) {
  const d = new Date(now)
  d.setDate(d.getDate() - n)
  return d.toISOString().split('T')[0]
}

function daysFromNow(n: number) {
  const d = new Date(now)
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

function yearFromDate(iso: string) {
  const d = new Date(iso)
  d.setFullYear(d.getFullYear() + 1)
  return d.toISOString().split('T')[0]
}

export const MOCK_MEMBERS: Member[] = [
  {
    id: '1',
    firstName: 'Robert',
    lastName: 'Johnson',
    birthdate: '1958-03-14',
    memberStatus: 'Active',
    dateJoined: '2018-09-01',
    address: '142 Maple Street',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    phone: '(217) 555-0142',
    email: 'rjohnson@email.com',
    lastDuesPaidDate: daysAgo(45),
    duesRenewalDate: yearFromDate(daysAgo(45)),
    duesReminderSentDate: undefined,
    notes: 'Longtime member. Helps organize the annual picnic. Prefers phone contact.',
    activity: [
      { id: 'a1', date: '2018-09-01', description: 'Member created' },
      { id: 'a2', date: daysAgo(45), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(45),
  },
  {
    id: '2',
    firstName: 'Thomas',
    lastName: 'Williams',
    birthdate: '1953-07-22',
    memberStatus: 'Active',
    dateJoined: '2015-04-12',
    address: '88 Oak Avenue',
    city: 'Riverside',
    state: 'IL',
    zip: '60546',
    phone: '(708) 555-0188',
    email: 'twilliams@email.com',
    lastDuesPaidDate: daysAgo(200),
    duesRenewalDate: daysFromNow(165),
    duesReminderSentDate: undefined,
    notes: 'Treasurer since 2019. Keep updated on financial reports.',
    activity: [
      { id: 'a1', date: '2015-04-12', description: 'Member created' },
      { id: 'a2', date: daysAgo(200), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(200),
  },
  {
    id: '3',
    firstName: 'Michael',
    lastName: 'Anderson',
    birthdate: '1961-11-30',
    memberStatus: 'Outstanding Dues',
    dateJoined: '2017-06-20',
    address: '305 Elm Court',
    city: 'Springfield',
    state: 'IL',
    zip: '62702',
    phone: '(217) 555-0305',
    email: 'manderson@email.com',
    lastDuesPaidDate: daysAgo(400),
    duesRenewalDate: daysAgo(35),
    duesReminderSentDate: daysAgo(14),
    notes: 'Has been contacted twice about overdue dues. Working through a difficult period.',
    activity: [
      { id: 'a1', date: '2017-06-20', description: 'Member created' },
      { id: 'a2', date: daysAgo(400), description: 'Dues payment recorded' },
      { id: 'a3', date: daysAgo(14), description: 'Dues reminder sent' },
    ],
    updatedAt: daysAgo(14),
  },
  {
    id: '4',
    firstName: 'James',
    lastName: 'Thompson',
    birthdate: '1966-02-08',
    memberStatus: 'Active',
    dateJoined: '2020-02-01',
    address: '717 Pine Road',
    city: 'Decatur',
    state: 'IL',
    zip: '62521',
    phone: '(217) 555-0717',
    email: 'jthompson@email.com',
    lastDuesPaidDate: daysAgo(10),
    duesRenewalDate: yearFromDate(daysAgo(10)),
    duesReminderSentDate: undefined,
    notes: '',
    activity: [
      { id: 'a1', date: '2020-02-01', description: 'Member created' },
      { id: 'a2', date: daysAgo(10), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(10),
  },
  {
    id: '5',
    firstName: 'David',
    lastName: 'Martinez',
    birthdate: '1955-09-17',
    memberStatus: 'Outstanding Dues',
    dateJoined: '2016-10-15',
    address: '22 Birch Lane',
    city: 'Springfield',
    state: 'IL',
    zip: '62703',
    phone: '(217) 555-0022',
    email: 'dmartinez@email.com',
    lastDuesPaidDate: daysAgo(380),
    duesRenewalDate: daysAgo(15),
    duesReminderSentDate: daysAgo(7),
    notes: 'Active volunteer. Usually pays by check. Contact at home after 5pm.',
    activity: [
      { id: 'a1', date: '2016-10-15', description: 'Member created' },
      { id: 'a2', date: daysAgo(380), description: 'Dues payment recorded' },
      { id: 'a3', date: daysAgo(7), description: 'Dues reminder sent' },
    ],
    updatedAt: daysAgo(7),
  },
  {
    id: '6',
    firstName: 'William',
    lastName: 'Garcia',
    birthdate: '1960-05-03',
    memberStatus: 'Former',
    dateJoined: '2014-03-08',
    address: '890 Cedar Blvd',
    city: 'Bloomington',
    state: 'IL',
    zip: '61701',
    phone: '(309) 555-0890',
    email: 'wgarcia@email.com',
    lastDuesPaidDate: daysAgo(730),
    duesRenewalDate: daysAgo(365),
    duesReminderSentDate: daysAgo(400),
    notes: 'Moved out of state. Marked former at member request.',
    activity: [
      { id: 'a1', date: '2014-03-08', description: 'Member created' },
      { id: 'a2', date: daysAgo(730), description: 'Dues payment recorded' },
      { id: 'a3', date: daysAgo(400), description: 'Dues reminder sent' },
      { id: 'a4', date: daysAgo(350), description: 'Status changed to Former' },
    ],
    updatedAt: daysAgo(350),
  },
  {
    id: '7',
    firstName: 'Richard',
    lastName: 'Lee',
    birthdate: '1963-08-25',
    memberStatus: 'Active',
    dateJoined: '2019-11-14',
    address: '55 Walnut Drive',
    city: 'Peoria',
    state: 'IL',
    zip: '61602',
    phone: '(309) 555-0055',
    email: 'rlee@email.com',
    lastDuesPaidDate: daysAgo(80),
    duesRenewalDate: yearFromDate(daysAgo(80)),
    duesReminderSentDate: undefined,
    notes: 'Prefers email communication. Board member.',
    activity: [
      { id: 'a1', date: '2019-11-14', description: 'Member created' },
      { id: 'a2', date: daysAgo(80), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(80),
  },
  {
    id: '8',
    firstName: 'Joseph',
    lastName: 'Harris',
    birthdate: '1950-12-01',
    memberStatus: 'Active',
    dateJoined: '2012-05-30',
    address: '1412 Spruce Way',
    city: 'Springfield',
    state: 'IL',
    zip: '62704',
    phone: '(217) 555-1412',
    email: 'jharris@email.com',
    lastDuesPaidDate: daysAgo(330),
    duesRenewalDate: daysFromNow(35),
    duesReminderSentDate: isoNow,
    notes: 'Founding member. Attended every annual meeting since 2012.',
    activity: [
      { id: 'a1', date: '2012-05-30', description: 'Member created' },
      { id: 'a2', date: daysAgo(330), description: 'Dues payment recorded' },
      { id: 'a3', date: isoNow, description: 'Dues reminder sent' },
    ],
    updatedAt: isoNow,
  },
  {
    id: '9',
    firstName: 'Charles',
    lastName: 'Clark',
    birthdate: '1957-04-18',
    memberStatus: 'Active',
    dateJoined: '2021-08-22',
    address: '333 Aspen Court',
    city: 'Champaign',
    state: 'IL',
    zip: '61820',
    phone: '(217) 555-0333',
    email: 'cclark@email.com',
    lastDuesPaidDate: daysAgo(120),
    duesRenewalDate: yearFromDate(daysAgo(120)),
    duesReminderSentDate: undefined,
    notes: '',
    activity: [
      { id: 'a1', date: '2021-08-22', description: 'Member created' },
      { id: 'a2', date: daysAgo(120), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(120),
  },
  {
    id: '10',
    firstName: 'George',
    lastName: 'Lewis',
    birthdate: '1959-06-14',
    memberStatus: 'Outstanding Dues',
    dateJoined: '2018-01-10',
    address: '67 Poplar Street',
    city: 'Rockford',
    state: 'IL',
    zip: '61101',
    phone: '(815) 555-0067',
    email: 'glewis@email.com',
    lastDuesPaidDate: daysAgo(420),
    duesRenewalDate: daysAgo(55),
    duesReminderSentDate: undefined,
    notes: 'Has not responded to reminder emails. Try calling.',
    activity: [
      { id: 'a1', date: '2018-01-10', description: 'Member created' },
      { id: 'a2', date: daysAgo(420), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(55),
  },
  {
    id: '11',
    firstName: 'Frank',
    lastName: 'Robinson',
    birthdate: '1962-10-09',
    memberStatus: 'Active',
    dateJoined: '2022-03-15',
    address: '489 Hickory Lane',
    city: 'Springfield',
    state: 'IL',
    zip: '62705',
    phone: '(217) 555-0489',
    email: 'frobinson@email.com',
    lastDuesPaidDate: daysAgo(60),
    duesRenewalDate: yearFromDate(daysAgo(60)),
    duesReminderSentDate: undefined,
    notes: 'Coach for youth baseball program.',
    activity: [
      { id: 'a1', date: '2022-03-15', description: 'Member created' },
      { id: 'a2', date: daysAgo(60), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(60),
  },
  {
    id: '12',
    firstName: 'Donald',
    lastName: 'Walker',
    birthdate: '1954-01-28',
    memberStatus: 'Former',
    dateJoined: '2013-07-04',
    address: '1001 Magnolia Drive',
    city: 'Peoria',
    state: 'IL',
    zip: '61603',
    phone: '(309) 555-1001',
    email: 'dwalker@email.com',
    lastDuesPaidDate: daysAgo(800),
    duesRenewalDate: daysAgo(435),
    duesReminderSentDate: daysAgo(500),
    notes: 'Health issues. Sent a card in December.',
    activity: [
      { id: 'a1', date: '2013-07-04', description: 'Member created' },
      { id: 'a2', date: daysAgo(800), description: 'Dues payment recorded' },
      { id: 'a3', date: daysAgo(500), description: 'Dues reminder sent' },
      { id: 'a4', date: daysAgo(430), description: 'Status changed to Former' },
    ],
    updatedAt: daysAgo(430),
  },
  {
    id: '13',
    firstName: 'Kenneth',
    lastName: 'Hall',
    birthdate: '1964-03-05',
    memberStatus: 'Active',
    dateJoined: '2023-01-20',
    address: '204 Sycamore Blvd',
    city: 'Decatur',
    state: 'IL',
    zip: '62522',
    phone: '(217) 555-0204',
    email: 'khall@email.com',
    lastDuesPaidDate: daysAgo(25),
    duesRenewalDate: yearFromDate(daysAgo(25)),
    duesReminderSentDate: undefined,
    notes: 'New member. Recruited by Robert Johnson.',
    activity: [
      { id: 'a1', date: '2023-01-20', description: 'Member created' },
      { id: 'a2', date: daysAgo(25), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(25),
  },
  {
    id: '14',
    firstName: 'Paul',
    lastName: 'Young',
    birthdate: '1956-08-12',
    memberStatus: 'Outstanding Dues',
    dateJoined: '2016-05-18',
    address: '778 Cottonwood Rd',
    city: 'Springfield',
    state: 'IL',
    zip: '62706',
    phone: '(217) 555-0778',
    email: 'pyoung@email.com',
    lastDuesPaidDate: daysAgo(395),
    duesRenewalDate: daysAgo(30),
    duesReminderSentDate: daysAgo(20),
    notes: '',
    activity: [
      { id: 'a1', date: '2016-05-18', description: 'Member created' },
      { id: 'a2', date: daysAgo(395), description: 'Dues payment recorded' },
      { id: 'a3', date: daysAgo(20), description: 'Dues reminder sent' },
    ],
    updatedAt: daysAgo(20),
  },
  {
    id: '15',
    firstName: 'Mark',
    lastName: 'Allen',
    birthdate: '1968-11-22',
    memberStatus: 'Active',
    dateJoined: '2021-09-10',
    address: '99 Linden Street',
    city: 'Joliet',
    state: 'IL',
    zip: '60432',
    phone: '(815) 555-0099',
    email: 'mallen@email.com',
    lastDuesPaidDate: daysAgo(150),
    duesRenewalDate: yearFromDate(daysAgo(150)),
    duesReminderSentDate: undefined,
    notes: 'Helps with the newsletter each month.',
    activity: [
      { id: 'a1', date: '2021-09-10', description: 'Member created' },
      { id: 'a2', date: daysAgo(150), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(150),
  },
  {
    id: '16',
    firstName: 'Steven',
    lastName: 'King',
    birthdate: '1952-07-07',
    memberStatus: 'Active',
    dateJoined: '2011-11-11',
    address: '512 Willow Way',
    city: 'Rockford',
    state: 'IL',
    zip: '61102',
    phone: '(815) 555-0512',
    email: 'sking@email.com',
    lastDuesPaidDate: daysAgo(95),
    duesRenewalDate: yearFromDate(daysAgo(95)),
    duesReminderSentDate: undefined,
    notes: 'Longest-tenured active member. Past president (2015–2018).',
    activity: [
      { id: 'a1', date: '2011-11-11', description: 'Member created' },
      { id: 'a2', date: daysAgo(95), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(95),
  },
  {
    id: '17',
    firstName: 'Daniel',
    lastName: 'Wright',
    birthdate: '1970-02-14',
    memberStatus: 'Active',
    dateJoined: '2022-06-01',
    address: '34 Chestnut Circle',
    city: 'Champaign',
    state: 'IL',
    zip: '61821',
    phone: '(217) 555-0034',
    email: 'dwright@email.com',
    lastDuesPaidDate: daysAgo(340),
    duesRenewalDate: daysFromNow(25),
    duesReminderSentDate: daysAgo(5),
    notes: '',
    activity: [
      { id: 'a1', date: '2022-06-01', description: 'Member created' },
      { id: 'a2', date: daysAgo(340), description: 'Dues payment recorded' },
      { id: 'a3', date: daysAgo(5), description: 'Dues reminder sent' },
    ],
    updatedAt: daysAgo(5),
  },
  {
    id: '18',
    firstName: 'Edward',
    lastName: 'Scott',
    birthdate: '1965-09-30',
    memberStatus: 'Former',
    dateJoined: '2017-04-22',
    address: '267 Beech Avenue',
    city: 'Bloomington',
    state: 'IL',
    zip: '61702',
    phone: '(309) 555-0267',
    email: 'escott@email.com',
    lastDuesPaidDate: daysAgo(600),
    duesRenewalDate: daysAgo(235),
    duesReminderSentDate: daysAgo(270),
    notes: 'Relocated. Left on good terms.',
    activity: [
      { id: 'a1', date: '2017-04-22', description: 'Member created' },
      { id: 'a2', date: daysAgo(600), description: 'Dues payment recorded' },
      { id: 'a3', date: daysAgo(270), description: 'Dues reminder sent' },
      { id: 'a4', date: daysAgo(240), description: 'Status changed to Former' },
    ],
    updatedAt: daysAgo(240),
  },
  {
    id: '19',
    firstName: 'Patrick',
    lastName: 'Green',
    birthdate: '1958-12-03',
    memberStatus: 'Active',
    dateJoined: '2020-10-05',
    address: '103 Juniper Drive',
    city: 'Peoria',
    state: 'IL',
    zip: '61604',
    phone: '(309) 555-0103',
    email: 'pgreen@email.com',
    lastDuesPaidDate: daysAgo(40),
    duesRenewalDate: yearFromDate(daysAgo(40)),
    duesReminderSentDate: undefined,
    notes: 'Veteran. Participates in community service events.',
    activity: [
      { id: 'a1', date: '2020-10-05', description: 'Member created' },
      { id: 'a2', date: daysAgo(40), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(40),
  },
  {
    id: '20',
    firstName: 'Raymond',
    lastName: 'Baker',
    birthdate: '1953-05-19',
    memberStatus: 'Outstanding Dues',
    dateJoined: '2015-08-28',
    address: '456 Alder Court',
    city: 'Joliet',
    state: 'IL',
    zip: '60433',
    phone: '(815) 555-0456',
    email: 'rbaker@email.com',
    lastDuesPaidDate: daysAgo(410),
    duesRenewalDate: daysAgo(45),
    duesReminderSentDate: undefined,
    notes: 'No contact yet this year. Dues overdue.',
    activity: [
      { id: 'a1', date: '2015-08-28', description: 'Member created' },
      { id: 'a2', date: daysAgo(410), description: 'Dues payment recorded' },
    ],
    updatedAt: daysAgo(45),
  },
]
